"""Versioned EPUB data-domain interfaces and implementations."""

from .store import (
    DuplicateEpubError,
    EpubStore,
    IntegrityError,
    SQLiteEpubStore,
    VersionCreation,
)
from .sqlite_vec import SQLiteVecHealth, SQLiteVecUnavailable, load_sqlite_vec
from .sqlite_vec_backend import SQLiteVecDerivedVectorBackend
from .inference import (
    ConceptResolver,
    EmbeddingService,
    JsonTransport,
    LocalConceptResolverAdapter,
    LocalEmbeddingAdapter,
    LocalEndpointRejected,
    LocalInferenceError,
    LocalInferenceUnavailable,
    LocalRerankerAdapter,
    ModelAvailability,
    PrivateModelEndpoint,
    RerankerService,
    UrllibJsonTransport,
)
from .vector_index import (
    DerivedVectorBackend,
    DerivedVectorIndexer,
    DerivedVectorRecord,
    InMemoryDerivedVectorBackend,
    IndexingResult,
    VectorIndexError,
)
from .search import (
    ConceptTerm,
    ConceptTermMatcher,
    EpubSearchRepository,
    EpubSearchService,
    SearchError,
    SearchExcerpt,
    SearchHit,
    SearchResponse,
    VectorCandidateBackend,
)
from .retrieval_units import (
    CHINESE_SENTENCE_ENDINGS,
    ENGLISH_SENTENCE_ENDINGS,
    OVERLAP_CODEPOINTS,
    TARGET_CODEPOINTS,
    RetrievalWindow,
    plan_retrieval_windows,
)

__all__ = [
    "DuplicateEpubError",
    "ConceptResolver",
    "CHINESE_SENTENCE_ENDINGS",
    "ConceptTerm",
    "ConceptTermMatcher",
    "DerivedVectorBackend",
    "DerivedVectorIndexer",
    "DerivedVectorRecord",
    "EmbeddingService",
    "ENGLISH_SENTENCE_ENDINGS",
    "EpubSearchRepository",
    "EpubSearchService",
    "EpubStore",
    "InMemoryDerivedVectorBackend",
    "IntegrityError",
    "IndexingResult",
    "JsonTransport",
    "LocalConceptResolverAdapter",
    "LocalEmbeddingAdapter",
    "LocalEndpointRejected",
    "LocalInferenceError",
    "LocalInferenceUnavailable",
    "LocalRerankerAdapter",
    "ModelAvailability",
    "OVERLAP_CODEPOINTS",
    "PrivateModelEndpoint",
    "RerankerService",
    "RetrievalWindow",
    "UrllibJsonTransport",
    "SearchError",
    "SearchExcerpt",
    "SearchHit",
    "SearchResponse",
    "SQLiteEpubStore",
    "SQLiteVecHealth",
    "SQLiteVecDerivedVectorBackend",
    "SQLiteVecUnavailable",
    "VersionCreation",
    "VectorIndexError",
    "VectorCandidateBackend",
    "TARGET_CODEPOINTS",
    "load_sqlite_vec",
    "plan_retrieval_windows",
]
