"""Derived vector-index boundary for faithful EPUB source passages.

This module is deliberately small and storage-engine-neutral.  A SQLite
``sqlite-vec`` implementation and a PostgreSQL ``pgvector`` implementation can
both implement :class:`DerivedVectorBackend`, while this service proves every
vector belongs to the exact immutable parent window before it reaches either
engine.  Vector backends receive hashes and offsets, never authority to rewrite
or cite source text.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import math
from typing import Any, Mapping, Protocol, Sequence

from .inference import EmbeddingService, ModelAvailability


class VectorIndexError(ValueError):
    """A vector index request would violate a source or profile invariant."""


@dataclass(frozen=True, slots=True)
class DerivedVectorRecord:
    """Metadata supplied to a vector backend for one immutable source window."""

    retrieval_unit_id: str
    passage_id: str
    start_codepoint: int
    end_codepoint: int
    content_sha256: str
    embedding_profile: str
    vector: tuple[float, ...]


@dataclass(frozen=True, slots=True)
class IndexingResult:
    """Index operation outcome that lets callers surface degraded local search."""

    retrieval_unit_id: str
    state: str
    availability: ModelAvailability
    reason: str | None = None


class DerivedSourceRepository(Protocol):
    """Minimal canonical-store read surface required for derived indexing."""

    def get_retrieval_unit(self, retrieval_unit_id: str) -> dict[str, Any] | None: ...

    def get_passage(self, passage_id: str) -> dict[str, Any] | None: ...


class DerivedVectorBackend(Protocol):
    """Storage implementation for vectors produced from verified source windows."""

    def upsert(self, record: DerivedVectorRecord) -> None: ...


class InMemoryDerivedVectorBackend:
    """Deterministic backend used for tests and non-persistent local diagnostics."""

    def __init__(self) -> None:
        self.records: dict[str, DerivedVectorRecord] = {}

    def upsert(self, record: DerivedVectorRecord) -> None:
        existing = self.records.get(record.retrieval_unit_id)
        if existing is not None and _identity(existing) != _identity(record):
            raise VectorIndexError(
                "a retrieval-unit ID cannot be rebound to a different source window or profile"
            )
        self.records[record.retrieval_unit_id] = record

    def search(
        self, query_vector: Sequence[float], *, embedding_profile: str, limit: int
    ) -> list[DerivedVectorRecord]:
        """Return nearest derived windows for deterministic tests/diagnostics.

        Production SQLite and PostgreSQL implementations use their native
        vector operators behind this identical boundary.  The in-memory
        implementation is intentionally strict about profile and dimensions so
        it cannot accidentally blend vectors generated by different models.
        """
        if limit < 1:
            raise VectorIndexError("vector search limit must be positive")
        query = _validated_vector(query_vector)
        scored: list[tuple[float, DerivedVectorRecord]] = []
        for record in self.records.values():
            if record.embedding_profile != embedding_profile:
                continue
            scored.append((_cosine(query, record.vector), record))
        scored.sort(key=lambda item: item[0], reverse=True)
        return [record for _, record in scored[:limit]]


class DerivedVectorIndexer:
    """Embeds only validated retrieval units with an explicitly local model.

    Unavailable local inference produces a ``DEGRADED`` result.  It does not
    invoke another adapter, a generic RAG client, or a cloud endpoint.
    """

    def __init__(
        self,
        *,
        source: DerivedSourceRepository,
        embeddings: EmbeddingService,
        backend: DerivedVectorBackend,
    ) -> None:
        self._source = source
        self._embeddings = embeddings
        self._backend = backend

    def index(self, retrieval_unit_id: str) -> IndexingResult:
        unit, passage = self._validated_source_window(retrieval_unit_id)
        availability = self._embeddings.availability()
        if not availability.available:
            return IndexingResult(
                retrieval_unit_id=retrieval_unit_id,
                state="DEGRADED",
                availability=availability,
                reason=availability.reason,
            )
        profile = unit.get("embedding_profile")
        if profile != self._embeddings.profile:
            raise VectorIndexError(
                "retrieval unit embedding_profile must exactly match the configured local embedding profile"
            )
        try:
            vectors = self._embeddings.embed([unit["content"]])
        except Exception as error:
            return IndexingResult(
                retrieval_unit_id=retrieval_unit_id,
                state="DEGRADED",
                availability=ModelAvailability.degraded("local-embedding", _safe_reason(error)),
                reason=_safe_reason(error),
            )
        if len(vectors) != 1:
            raise VectorIndexError("local embedding service must return exactly one vector per source window")
        vector = _validated_vector(vectors[0])
        record = DerivedVectorRecord(
            retrieval_unit_id=retrieval_unit_id,
            passage_id=str(unit["passage_id"]),
            start_codepoint=int(unit["start_codepoint"]),
            end_codepoint=int(unit["end_codepoint"]),
            content_sha256=str(unit["content_sha256"]),
            embedding_profile=str(profile),
            vector=vector,
        )
        self._backend.upsert(record)
        return IndexingResult(
            retrieval_unit_id=retrieval_unit_id,
            state="READY",
            availability=availability,
        )

    def _validated_source_window(
        self, retrieval_unit_id: str
    ) -> tuple[Mapping[str, Any], Mapping[str, Any]]:
        unit = self._source.get_retrieval_unit(retrieval_unit_id)
        if unit is None:
            raise VectorIndexError(f"unknown retrieval_unit_id: {retrieval_unit_id}")
        passage_id = unit.get("passage_id")
        if not isinstance(passage_id, str) or not passage_id:
            raise VectorIndexError("retrieval unit has no valid parent passage ID")
        passage = self._source.get_passage(passage_id)
        if passage is None:
            raise VectorIndexError("retrieval unit parent passage is missing")
        content = passage.get("content")
        unit_content = unit.get("content")
        start = unit.get("start_codepoint")
        end = unit.get("end_codepoint")
        if not isinstance(content, str) or not isinstance(unit_content, str):
            raise VectorIndexError("source passage and retrieval unit content must be text")
        if not isinstance(start, int) or not isinstance(end, int) or start < 0 or end <= start or end > len(content):
            raise VectorIndexError("retrieval-unit offsets must identify a non-empty parent source substring")
        expected = content[start:end]
        if unit_content != expected:
            raise VectorIndexError("retrieval-unit content does not equal its exact parent source window")
        if unit.get("content_sha256") != _text_hash(expected):
            raise VectorIndexError("retrieval-unit content hash does not match its exact parent source window")
        return unit, passage


def _identity(record: DerivedVectorRecord) -> tuple[str, str, int, int, str, str]:
    return (
        record.retrieval_unit_id,
        record.passage_id,
        record.start_codepoint,
        record.end_codepoint,
        record.content_sha256,
        record.embedding_profile,
    )


def _text_hash(value: str) -> str:
    return sha256(value.encode("utf-8")).hexdigest()


def _validated_vector(vector: Sequence[float]) -> tuple[float, ...]:
    if not vector:
        raise VectorIndexError("local embedding service returned an empty vector")
    values: list[float] = []
    for value in vector:
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
            raise VectorIndexError("local embedding service returned a non-finite vector value")
        values.append(float(value))
    return tuple(values)


def _cosine(left: Sequence[float], right: Sequence[float]) -> float:
    if len(left) != len(right) or not left:
        raise VectorIndexError("vector query and index record dimensions must match")
    left_norm = math.sqrt(sum(value * value for value in left))
    right_norm = math.sqrt(sum(value * value for value in right))
    if not left_norm or not right_norm:
        return 0.0
    return sum(a * b for a, b in zip(left, right)) / (left_norm * right_norm)


def _safe_reason(error: Exception) -> str:
    return (str(error).strip() or type(error).__name__)[:240]
